apiVersion: v1
kind: Service
metadata:
  name: helpdesk-web
  namespace: helpdesk

  labels:
    app: helpdesk-web
spec:
  selector:
    app: helpdesk-web

  ports:
    - name: http
      port: 80
      targetPort: 5000

  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helpdesk-web
  namespace: helpdesk
spec:
  replicas: 1

  selector:
    matchLabels:
      app: helpdesk-web

  template:
    metadata:
      labels:
        app: helpdesk-web

    spec:
      imagePullSecrets:
        - name: ghcr-credentials

      initContainers:
        - name: wait-for-postgres
          image: postgres:17-alpine

          command:
            - /bin/sh
            - -c
            - |
              until pg_isready \
                  -h postgres \
                  -U "$POSTGRES_USER" \
                  -d "$POSTGRES_DB";
              do
                  echo "Waiting for PostgreSQL..."
                  sleep 2
              done

          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: helpdesk-secrets
                  key: POSTGRES_DB

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: helpdesk-secrets
                  key: POSTGRES_USER

      containers:
        - name: helpdesk-web
          image: ghcr.io/haroonranaspy7/devops-helpdesk:2083431b15c1d0c9b2b03e60930ac87a60ae40c6
          imagePullPolicy: Always

          ports:
            - name: http
              containerPort: 5000

          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: helpdesk-secrets
                  key: DATABASE_URL

            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: helpdesk-secrets
                  key: SECRET_KEY

          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
      terminationGracePeriodSeconds: 30
