apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: rancher.io/local-path
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: false

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helpdesk-web
  namespace: helpdesk
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - 18-210-115-168.sslip.io
      secretName: helpdesk-tls
  rules:
    - host: 18-210-115-168.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: helpdesk-web
                port:
                  number: 80
